### ISSUE TITLE
Executable command misnamed

### ISSUE THREAD

**Issue by iCodeSometime** [defra91/bitbucket-issue-manager#6]
It seems there are several locations where bitbucket is misspelled as bitbucker.
This caused a good deal of confusion until I searched my npm package folder.

The docs seem to mostly refer to the command as bitbucket, but in one location refer to bitbucker-issue-manager.

[misspelled references](https://github.com/defra91/bitbucket-issue-manager/search?utf8=%E2%9C%93&q=bitbucker&type=)

**Comment by iCodeSometime** [comment]
Sorry, missed the existing pull request to fix this.

**Comment by gustavofuhr** [comment]
Yet, the current npm is installing the version with the typo. It's a bit confusing since the install instructions don't have the typo.
